import { GFACategory } from './revit-models'


export class ListCategories{
    list: GFACategory[] = [
        { levelElementName: 'ETS ROOM 503', category: 'GFA - Non Sellable' },
{ levelElementName: 'LV ROOM 504', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'TRANSFORMER RM 505', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'LIFT SHAFT 507', category: 'GFA - Non Sellable' },
{ levelElementName: 'MAIN LOBBY 537', category: 'GFA - Non Sellable' },
{ levelElementName: 'STAIRS 695', category: 'GFA - Non Sellable' },
{ levelElementName: 'CONTROL/FCC/BMS ROOM 588', category: 'GFA - Non Sellable' },
{ levelElementName: 'GARBAGE ROOM 589', category: 'GFA - Non Sellable' },
{ levelElementName: 'STAIRS 590', category: 'GFA - Non Sellable' },
{ levelElementName: 'GENERATOR ROOM 1010', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'SHADED AREA 1015', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM 564', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'DRIVEWAY/RAMP 948', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'LIFT LOBBY 1053', category: 'GFA - Non Sellable' },
{ levelElementName: 'STAIRS 1054', category: 'GFA - Non Sellable' },
{ levelElementName: 'STAIRS 1055', category: 'GFA - Non Sellable' },
{ levelElementName: 'WATER MTR. 1016', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 1017', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 1018', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'LIFT LOBBY 1019', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 1020', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 1021', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 1022', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 1023', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 1024', category: 'GFA - Non Sellable' },
{ levelElementName: 'GYM 1025', category: 'GFA - Non Sellable' },
{ levelElementName: 'PRAYER ROOM 1028', category: 'GFA - Non Sellable' },
{ levelElementName: 'MULTIPURPOSE ROOM 1029', category: 'GFA - Non Sellable' },
{ levelElementName: 'TOILET 1035', category: 'GFA - Non Sellable' },
{ levelElementName: 'toilet 20', category: 'n/a' },
{ levelElementName: '1BDRM - TYPE 02 1037', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 1038', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 01 1039', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 1040', category: 'GFA - Sellable' },
{ levelElementName: 'WATER MTR. 1041', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 1042', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 1043', category: 'Non GFA - Non Sellable' },
{ levelElementName: '2BDRM- TYPE 01 1046', category: 'GFA - Sellable' },
{ levelElementName: 'LIFT LOBBY 1047', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 1048', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 1049', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 1050', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 1051', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 1052', category: 'GFA - Non Sellable' },
{ levelElementName: 'BALCONY 1091', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1092', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1093', category: 'Non GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 01 509', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 510', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 511', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 01 513', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 514', category: 'GFA - Sellable' },
{ levelElementName: 'WATER MTR. 516', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 517', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 519', category: 'Non GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 521', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 522', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM- TYPE 01 523', category: 'GFA - Sellable' },
{ levelElementName: 'LIFT LOBBY 524', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 525', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 526', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 527', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 528', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 529', category: 'GFA - Non Sellable' },
{ levelElementName: 'BALCONY 731', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 732', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 733', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 734', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 735', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 736', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 737', category: 'Non GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 01 530', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 531', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 532', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 01 533', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 534', category: 'GFA - Sellable' },
{ levelElementName: 'WATER MTR. 535', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 538', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 539', category: 'Non GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 540', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 541', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM- TYPE 01 542', category: 'GFA - Sellable' },
{ levelElementName: 'LIFT LOBBY 543', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 544', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 545', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 546', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 547', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 548', category: 'GFA - Non Sellable' },
{ levelElementName: 'BALCONY 738', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 739', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 740', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 741', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 742', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 743', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 744', category: 'Non GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 01 549', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 550', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 551', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 01 552', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 553', category: 'GFA - Sellable' },
{ levelElementName: 'WATER MTR. 554', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 555', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 557', category: 'Non GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 560', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 570', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM- TYPE 01 571', category: 'GFA - Sellable' },
{ levelElementName: 'LIFT LOBBY 572', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 573', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 574', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 575', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 576', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 577', category: 'GFA - Non Sellable' },
{ levelElementName: 'BALCONY 1056', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1057', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1058', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1059', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1060', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1061', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1062', category: 'Non GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 01 578', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 579', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 580', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 01 581', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 584', category: 'GFA - Sellable' },
{ levelElementName: 'WATER MTR. 585', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 586', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 587', category: 'Non GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 591', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 592', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM- TYPE 01 593', category: 'GFA - Sellable' },
{ levelElementName: 'LIFT LOBBY 594', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 595', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 596', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 597', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 598', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 599', category: 'GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 600', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 601', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 602', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 01 603', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 604', category: 'GFA - Sellable' },
{ levelElementName: 'WATER MTR. 605', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 606', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 607', category: 'Non GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 608', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 609', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM- TYPE 01 610', category: 'GFA - Sellable' },
{ levelElementName: 'LIFT LOBBY 611', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 612', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 613', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 614', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 615', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 616', category: 'GFA - Non Sellable' },
{ levelElementName: 'BALCONY 1063', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1064', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1065', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1066', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1067', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1068', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1069', category: 'Non GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 01 617', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 618', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 619', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 01 620', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 621', category: 'GFA - Sellable' },
{ levelElementName: 'WATER MTR. 622', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 623', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 624', category: 'Non GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 625', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 626', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM- TYPE 01 627', category: 'GFA - Sellable' },
{ levelElementName: 'LIFT LOBBY 628', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 629', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 630', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 631', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 632', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 633', category: 'GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 634', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 635', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 636', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 01 637', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 638', category: 'GFA - Sellable' },
{ levelElementName: 'WATER MTR. 639', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 640', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 641', category: 'Non GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 642', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 643', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM- TYPE 01 644', category: 'GFA - Sellable' },
{ levelElementName: 'LIFT LOBBY 645', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 646', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 647', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 648', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 649', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 650', category: 'GFA - Non Sellable' },
{ levelElementName: 'BALCONY 1070', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1071', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1072', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1073', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1074', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1075', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1076', category: 'Non GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 01 651', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 652', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 653', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 01 654', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 655', category: 'GFA - Sellable' },
{ levelElementName: 'WATER MTR. 656', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 657', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 658', category: 'Non GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 659', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 660', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM- TYPE 01 661', category: 'GFA - Sellable' },
{ levelElementName: 'LIFT LOBBY 662', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 663', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 664', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 665', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 666', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 667', category: 'GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 668', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 669', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 670', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 01 671', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 672', category: 'GFA - Sellable' },
{ levelElementName: 'WATER MTR. 673', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 674', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 675', category: 'Non GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 676', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 677', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM- TYPE 01 678', category: 'GFA - Sellable' },
{ levelElementName: 'LIFT LOBBY 679', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 680', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 681', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 682', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 683', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 684', category: 'GFA - Non Sellable' },
{ levelElementName: 'BALCONY 1077', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1078', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1079', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1080', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1081', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1082', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1083', category: 'Non GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 01 685', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 686', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 687', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 01 688', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 689', category: 'GFA - Sellable' },
{ levelElementName: 'WATER MTR. 690', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 691', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 692', category: 'Non GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 693', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 694', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM- TYPE 01 696', category: 'GFA - Sellable' },
{ levelElementName: 'LIFT LOBBY 697', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 698', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 699', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 700', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 701', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 702', category: 'GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 703', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 704', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 705', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 01 706', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 03 707', category: 'GFA - Sellable' },
{ levelElementName: 'WATER MTR. 708', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 711', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 712', category: 'Non GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 01 713', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02 714', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM- TYPE 01 715', category: 'GFA - Sellable' },
{ levelElementName: 'LIFT LOBBY 716', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 717', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 718', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 719', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 720', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 721', category: 'GFA - Non Sellable' },
{ levelElementName: 'BALCONY 1084', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1085', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1086', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1087', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1088', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1089', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1090', category: 'Non GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 03 444', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 02 463', category: 'GFA - Sellable' },
{ levelElementName: '3BDRM - TYPE 1 472', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 02 892', category: 'GFA - Sellable' },
{ levelElementName: 'BALCONY 1026', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1027', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1030', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1031', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1032', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1033', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 1034', category: 'Non GFA - Sellable' },
{ levelElementName: 'WATER MTR. 722', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 723', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 724', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'LIFT LOBBY 725', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 726', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 727', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 728', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 729', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 730', category: 'GFA - Non Sellable' },
{ levelElementName: '2BDRM - TYPE 03 893', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 02 894', category: 'GFA - Sellable' },
{ levelElementName: '3BDRM - TYPE 1 895', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 02 897', category: 'GFA - Sellable' },
{ levelElementName: 'BALCONY 899', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 900', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 901', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 902', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 903', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 904', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 905', category: 'Non GFA - Sellable' },
{ levelElementName: 'WATER MTR. 906', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 907', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 908', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'LIFT LOBBY 909', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 910', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 911', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 912', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 913', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 914', category: 'GFA - Non Sellable' },
{ levelElementName: '2BDRM - TYPE 03 915', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 02 916', category: 'GFA - Sellable' },
{ levelElementName: '3BDRM - TYPE 1 917', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 02 918', category: 'GFA - Sellable' },
{ levelElementName: 'BALCONY 919', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 920', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 921', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 922', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 923', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 924', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 925', category: 'Non GFA - Sellable' },
{ levelElementName: 'WATER MTR. 926', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 927', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 928', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'LIFT LOBBY 929', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 930', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 931', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 932', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 936', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 937', category: 'GFA - Non Sellable' },
{ levelElementName: '2BDRM - TYPE 03 938', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 02 939', category: 'GFA - Sellable' },
{ levelElementName: '3BDRM - TYPE 1 942', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 02 950', category: 'GFA - Sellable' },
{ levelElementName: 'BALCONY 951', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 952', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 953', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 954', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 955', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 956', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 957', category: 'Non GFA - Sellable' },
{ levelElementName: 'WATER MTR. 958', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 959', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 960', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'LIFT LOBBY 961', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 962', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 963', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 964', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 965', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 966', category: 'GFA - Non Sellable' },
{ levelElementName: '2BDRM - TYPE 03 967', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 02 968', category: 'GFA - Sellable' },
{ levelElementName: '3BDRM - TYPE 1 969', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 02 970', category: 'GFA - Sellable' },
{ levelElementName: 'BALCONY 971', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 972', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 973', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 974', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 975', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 976', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 977', category: 'Non GFA - Sellable' },
{ levelElementName: 'WATER MTR. 978', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 981', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 982', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'LIFT LOBBY 983', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 984', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 985', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 986', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 987', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 988', category: 'GFA - Non Sellable' },
{ levelElementName: '2BDRM - TYPE 03 989', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 02 990', category: 'GFA - Sellable' },
{ levelElementName: '3BDRM - TYPE 1 991', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 02 992', category: 'GFA - Sellable' },
{ levelElementName: 'BALCONY 993', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 994', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 995', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 996', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 997', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 998', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY 999', category: 'Non GFA - Sellable' },
{ levelElementName: 'WATER MTR. 1000', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'ELEC. RM. 1001', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'FHC 1002', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'LIFT LOBBY 1003', category: 'GFA - Non Sellable' },
{ levelElementName: 'IT RM. 1008', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 1011', category: 'GFA - Non Sellable' },
{ levelElementName: 'GAR. RM. 1012', category: 'GFA - Non Sellable' },
{ levelElementName: 'FHC 1013', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 1014', category: 'GFA - Non Sellable' },
{ levelElementName: '', category: 'n/a' },
{ levelElementName: 'WATER TANK 475', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'PUMP ROOM 492', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'CORRIDOR 1004', category: 'GFA - Non Sellable' },
{ levelElementName: 'STAIRS 1005', category: 'GFA - Non Sellable' },
{ levelElementName: 'STAIRS 1006', category: 'GFA - Non Sellable' },
{ levelElementName: 'SCHW  PUMP ROOM 1007', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'MDF ROOM 1009', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'CIRCULATION 21', category: 'GFA - Non Sellable' },
{ levelElementName: 'CIRCULATION 22', category: 'GFA - Non Sellable' },
{ levelElementName: 'STAIRS 709', category: 'GFA - Non Sellable' },
{ levelElementName: 'STAIRS 710', category: 'GFA - Non Sellable' },
{ levelElementName: 'LIFT LOBBY 940', category: 'GFA - Non Sellable' },
{ levelElementName: 'STAIRS 941', category: 'GFA - Non Sellable' },
{ levelElementName: 'DRIVEWAY/RAMP 944', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'STAIRS 945', category: 'GFA - Non Sellable' },
{ levelElementName: 'DEDUCTION 1601', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'MAIN TEL. ROOM 731', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'BALCONY (UNSHADED) 746', category: 'Non GFA - Sellable' },
{ levelElementName: 'BALCONY', category: 'Non GFA - Sellable' },
{ levelElementName: 'SHAFT 1000', category: 'Non GFA - Non Sellable' },
{ levelElementName: 'WMR 1000', category: 'Non GFA - Non Sellable' },
{ levelElementName: '1BDRM - TYPE 03A 1000', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 04 1000', category: 'GFA - Sellable' },
{ levelElementName: '1BDRM - TYPE 02A 1000', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 04 1000', category: 'GFA - Sellable' },
{ levelElementName: '2BDRM - TYPE 05 1000', category: 'GFA - Sellable' },
]
}