import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class PlannerService {
  private AccessToken = 'eyJ0eXAiOiJKV1QiLCJub25jZSI6ImE0LU83aHkxdFA5UjhuWVdaUnZqd2czQXJJWmUxZ1ptZTk0Q25aQ05laGMiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC82ZWYyMTU3OS1hY2UxLTQzOTItYWMzMi1kNTQ4OTM5Yzc0YTIvIiwiaWF0IjoxNjE1ODcwNjQwLCJuYmYiOjE2MTU4NzA2NDAsImV4cCI6MTYxNTg3NDU0MCwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iLCJ1cm46bWljcm9zb2Z0OnJlcTEiLCJ1cm46bWljcm9zb2Z0OnJlcTIiLCJ1cm46bWljcm9zb2Z0OnJlcTMiLCJjMSIsImMyIiwiYzMiLCJjNCIsImM1IiwiYzYiLCJjNyIsImM4IiwiYzkiLCJjMTAiLCJjMTEiLCJjMTIiLCJjMTMiLCJjMTQiLCJjMTUiLCJjMTYiLCJjMTciLCJjMTgiLCJjMTkiLCJjMjAiLCJjMjEiLCJjMjIiLCJjMjMiLCJjMjQiLCJjMjUiXSwiYWlvIjoiRTJaZ1lOZ2w3KzI5cnFQLzViV3EyK1gydkhkVWJ1VFl2ellUVUZEVitjVzM5dVFPN1VVQSIsImFtciI6WyJwd2QiXSwiYXBwX2Rpc3BsYXluYW1lIjoiR3JhcGggZXhwbG9yZXIgKG9mZmljaWFsIHNpdGUpIiwiYXBwaWQiOiJkZThiYzhiNS1kOWY5LTQ4YjEtYThhZC1iNzQ4ZGE3MjUwNjQiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6Ik11c2h0YXEiLCJnaXZlbl9uYW1lIjoiTW9oc2luIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMi41MC4zNS4xMzYiLCJuYW1lIjoiTW9oc2luIE11c2h0YXEiLCJvaWQiOiIxZjlhMmY2ZS1hOWM4LTRhOTItOWY3Ny0zNDJhNzcyZDdiM2QiLCJwbGF0ZiI6IjMiLCJwdWlkIjoiMTAwMzIwMDExQUMxRTgyQSIsInJoIjoiMC5BQUFBZVJYeWJ1R3Nra09zTXRWSWs1eDBvclhJaTk3NTJiRklxSzIzU05weVVHUklBRUUuIiwic2NwIjoiQ2FsZW5kYXJzLlJlYWRXcml0ZSBDb250YWN0cy5SZWFkV3JpdGUgRmlsZXMuUmVhZFdyaXRlLkFsbCBHcm91cC5SZWFkLkFsbCBHcm91cC5SZWFkV3JpdGUuQWxsIE1haWwuUmVhZFdyaXRlIE5vdGVzLlJlYWRXcml0ZS5BbGwgb3BlbmlkIFBlb3BsZS5SZWFkIHByb2ZpbGUgU2l0ZXMuUmVhZFdyaXRlLkFsbCBUYXNrcy5SZWFkV3JpdGUgVXNlci5SZWFkIFVzZXIuUmVhZC5BbGwgVXNlci5SZWFkQmFzaWMuQWxsIFVzZXIuUmVhZFdyaXRlIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiejRtNXZkYnVvam5VN3Itd1hROE5KaHVWN3VwaVh1YjJUaWM1NDdYQlowZyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJFVSIsInRpZCI6IjZlZjIxNTc5LWFjZTEtNDM5Mi1hYzMyLWQ1NDg5MzljNzRhMiIsInVuaXF1ZV9uYW1lIjoibW9oc2luLm11c2h0YXFAYXJjaGNvcnAuYml6IiwidXBuIjoibW9oc2luLm11c2h0YXFAYXJjaGNvcnAuYml6IiwidXRpIjoiYVp0MngzUjVzRW1yMjZiS2xOeFVBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJqZElPeThaWHY3akhQTWxtNklETklpZDZJZzh5RzBheGtpTFR4WnQwRjdzIn0sInhtc190Y2R0IjoxNDIwNzAwODY1fQ.i9LOO7TlfDDrPj5Ft-ZqMb33R5RKPkkClFJVsF_DB6LQT3o7WqfssOCkRsaoWFPG5fl02Uf_DA5IzJtQxAi05cYuclj_v-YGzocMlHbdWDV2iwEtnvQOECeHTflagjOOit9APwwD9BFVgGSvITPIWJQpJdgIQoYlz7DmmWODtHSHLXFFcM7u0vW70V__bVRZnGtIT-kTExAYQirjOSKjIuR8wajOFtG3ya_I-b5HJrbGSDy8Xs5SlSgsaNFu5Oc1HRu-E9NUTBg6PAxyJpSqajq_ziNU1Iybc9mmPAAfjMAYD1ICyLev0_LOjQhXY_3Z11Hb7uj3-Yif0AsbRsUunQ';
    
  private PLANNER_URL = "https://graph.microsoft.com/v1.0/planner/plans/yTFS6Y2Gt06AUGDSzIp75JcACDAI/tasks";
  private USER_URL ="https://graph.microsoft.com/v1.0/users/";
  constructor(private http: HttpClient) { }

  getAllTask(){
    const header = {
      headers: new HttpHeaders()
        .set('Authorization',  `Bearer ${this.AccessToken}`)
    }  
    return this.http.get(this.PLANNER_URL,header);
  }

  getUserName(id:string){
    const header = {
      headers: new HttpHeaders()
        .set('Authorization',  `Bearer ${this.AccessToken}`)
    } 
    return this.http.get(this.USER_URL + id, header);
  }
}
